substitutions:
  _SERVICE_NAME: case-service
  _REGION: us-central1
  _REPO: lms-services
  _CLOUDSQL_PUBLIC_IP: "34.41.188.59"

steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - 'build'
      - '-f'
      - 'case-service/Dockerfile'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--port=8083'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--service-account=lms-case-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-secrets=DB_PASSWORD=auth-db-password:latest,JWT_SECRET=auth-jwt-secret:latest,SPRING_RABBITMQ_URI=cloudamqp-url:latest'
      - '--set-env-vars=SPRING_DATASOURCE_URL=jdbc:mysql://${_CLOUDSQL_PUBLIC_IP}:3306/legal_management_db?useSSL=true&requireSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true,DB_USER=root,HIBERNATE_DDL_AUTO=update'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
