version: "3.9"

services:

mysql:
image: mysql:8
container_name: legal_mysql
restart: always
environment:
MYSQL_ROOT_PASSWORD: root
MYSQL_DATABASE: legal_system
ports:
- "3306:3306"
volumes:
- mysql_data:/var/lib/mysql

rabbitmq:
image: rabbitmq:3-management
container_name: legal_rabbitmq
ports:
- "5672:5672"
- "15672:15672"

api-gateway:
build: ./backend/api-gateway
container_name: api_gateway
depends_on:
- auth-service
- user-service
- case-service
ports:
- "8080:8080"

auth-service:
build: ./backend/auth-service
container_name: auth_service
depends_on:
- mysql
- rabbitmq
environment:
SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/legal_system
SPRING_DATASOURCE_USERNAME: root
SPRING_DATASOURCE_PASSWORD: root

user-service:
build: ./backend/user-service
container_name: user_service
depends_on:
- mysql
- rabbitmq
environment:
SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/legal_system
SPRING_DATASOURCE_USERNAME: root
SPRING_DATASOURCE_PASSWORD: root

case-service:
build: ./backend/case-service
container_name: case_service
depends_on:
- mysql
- rabbitmq
environment:
SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/legal_system
SPRING_DATASOURCE_USERNAME: root
SPRING_DATASOURCE_PASSWORD: root

document-service:
build: ./backend/document-service
container_name: document_service
depends_on:
- mysql
- rabbitmq
environment:
SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/legal_system
SPRING_DATASOURCE_USERNAME: root
SPRING_DATASOURCE_PASSWORD: root

notification-service:
build: ./backend/notification-service
container_name: notification_service
depends_on:
- rabbitmq

volumes:
mysql_data:
