apiVersion: v1
kind: Secret
metadata:
  name: legal-oauth-secrets
  namespace: legal-system-prod
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  GH_CLIENT_ID: "${GH_CLIENT_ID}"
  GH_CLIENT_SECRET: "${GH_CLIENT_SECRET}"