spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://legal-case-system-db.cg5ygkuo00d4.us-east-1.rds.amazonaws.com:3306/legal_management_db?useSSL=true&requireSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082


logging:
  level:
    com.legal.user: DEBUG

jwt:
  secret: ${JWT_SECRET}
  issuer: legal-management-system
