spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@eureka-server:${server.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO

jwt:
  secret: ${JWT_SECRET}
  issuer: legal-management-system
